name: Docker Image CI

on:
  push:
    branches: [ "main-2" ]
  pull_request:
    branches: [ "main-2" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag react-app:$(date -u +%Y-%m-%d-%H%M%S)
